wsdata.wscall.*:
  type: config_entity
  label: 'Web Service Call config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    wsserver:
      label: 'WS Server'
      type: string
    wsdecoder:
      label: 'WS Decoder'
      type: string
    wsencoder:
      label: 'WS Encoder'
      type: string
    options:
      label: 'Options'
      type: struct
