wsdata.wsserver.*:
  type: config_entity
  label: 'Web Service Server config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    endpoint:
      label: 'Endpoint'
      type: string
    wsconnector:
      label: 'WS Connector'
      type: string
    languagehandling:
      label: 'Language Handling'
      type: struct
    settings:
      label: 'Settings'
      type: struct
